{
  "timestamp": "2025-09-24T05:00:06.307322",
  "duration_seconds": 1.731575,
  "return_code": 1,
  "stdout": "============================= test session starts ==============================\nplatform darwin -- Python 3.9.6, pytest-7.4.3, pluggy-1.6.0 -- /Users/dmitrypavlyuchenkov/TelegramBot/venv/bin/python\ncachedir: .pytest_cache\nrootdir: /Users/dmitrypavlyuchenkov/HackReality-MainBot\nconfigfile: pytest.ini\nplugins: mock-3.15.1, anyio-4.11.0, cov-4.1.0, asyncio-0.21.1\nasyncio: mode=strict\ncollecting ... collected 59 items\n\ntests/test_admin_notifications.py::TestAdminNotifications::test_new_user_notification ERROR [  1%]\ntests/test_admin_notifications.py::TestAdminNotifications::test_new_subscription_notification ERROR [  3%]\ntests/test_admin_notifications.py::TestAdminNotifications::test_payment_notification ERROR [  5%]\ntests/test_admin_notifications.py::TestAdminNotifications::test_help_request_notification ERROR [  6%]\ntests/test_admin_notifications.py::TestAdminNotifications::test_notification_error_handling ERROR [  8%]\ntests/test_admin_notifications.py::TestAdminNotifications::test_notification_with_missing_user_data ERROR [ 10%]\ntests/test_admin_notifications.py::TestAdminNotifications::test_notification_formatting ERROR [ 11%]\ntests/test_admin_notifications.py::TestAdminNotifications::test_multiple_notifications ERROR [ 13%]\ntests/test_admin_notifications.py::TestAdminNotifications::test_notification_with_special_characters ERROR [ 15%]\ntests/test_bug_demonstration.py::TestBugDemonstration::test_bug_demonstration PASSED [ 16%]\ntests/test_bug_demonstration.py::TestBugDemonstration::test_fix_demonstration FAILED [ 18%]\ntests/test_bug_demonstration.py::TestBugDemonstration::test_onboarding_flow_bug_demonstration PASSED [ 20%]\ntests/test_bug_demonstration.py::TestBugDemonstration::test_fixed_onboarding_flow FAILED [ 22%]\ntests/test_bug_summary.py::TestBugSummary::test_bug_summary PASSED       [ 23%]\ntests/test_bug_summary.py::TestBugSummary::test_automated_testing_benefits PASSED [ 25%]\ntests/test_database_operations.py::TestDatabaseOperations::test_database_initialization FAILED [ 27%]\ntests/test_database_operations.py::TestDatabaseOperations::test_user_initialization FAILED [ 28%]\ntests/test_database_operations.py::TestDatabaseOperations::test_user_state_management FAILED [ 30%]\ntests/test_database_operations.py::TestDatabaseOperations::test_user_state_updates FAILED [ 32%]\ntests/test_database_operations.py::TestDatabaseOperations::test_message_storage FAILED [ 33%]\ntests/test_database_operations.py::TestDatabaseOperations::test_subscription_management FAILED [ 35%]\ntests/test_database_operations.py::TestDatabaseOperations::test_focus_statements_management FAILED [ 37%]\ntests/test_database_operations.py::TestDatabaseOperations::test_task_management FAILED [ 38%]\ntests/test_database_operations.py::TestDatabaseOperations::test_active_task_management FAILED [ 40%]\ntests/test_database_operations.py::TestDatabaseOperations::test_database_concurrent_access FAILED [ 42%]\ntests/test_message_routing.py::TestMessageRouting::test_start_command_routes_to_onboarding ERROR [ 44%]\ntests/test_message_routing.py::TestMessageRouting::test_message_routing_by_state ERROR [ 45%]\ntests/test_message_routing.py::TestMessageRouting::test_callback_query_routing_by_state ERROR [ 47%]\ntests/test_message_routing.py::TestMessageRouting::test_unknown_state_routes_to_onboarding ERROR [ 49%]\ntests/test_message_routing.py::TestMessageRouting::test_none_state_routes_to_onboarding ERROR [ 50%]\ntests/test_message_routing.py::TestMessageRouting::test_message_routing_with_security_checks ERROR [ 52%]\ntests/test_message_routing.py::TestMessageRouting::test_callback_query_routing_with_security_checks ERROR [ 54%]\ntests/test_message_routing.py::TestMessageRouting::test_rate_limit_blocking ERROR [ 55%]\ntests/test_message_routing.py::TestMessageRouting::test_invalid_input_handling ERROR [ 57%]\ntests/test_message_routing.py::TestMessageRouting::test_error_handling_in_routing ERROR [ 59%]\ntests/test_onboarding_flow.py::TestOnboardingFlow::test_start_onboarding_sets_correct_state ERROR [ 61%]\ntests/test_onboarding_flow.py::TestOnboardingFlow::test_welcome_message_sends_correct_content ERROR [ 62%]\ntests/test_onboarding_flow.py::TestOnboardingFlow::test_continue_onboarding_button_advances_step ERROR [ 64%]\ntests/test_onboarding_flow.py::TestOnboardingFlow::test_disclaimer_acceptance_advances_flow ERROR [ 66%]\ntests/test_onboarding_flow.py::TestOnboardingFlow::test_age_collection_handles_valid_input ERROR [ 67%]\ntests/test_onboarding_flow.py::TestOnboardingFlow::test_age_collection_handles_invalid_input ERROR [ 69%]\ntests/test_onboarding_flow.py::TestOnboardingFlow::test_city_collection_stores_city ERROR [ 71%]\ntests/test_onboarding_flow.py::TestOnboardingFlow::test_onboarding_completion_sets_final_state ERROR [ 72%]\ntests/test_onboarding_flow.py::TestOnboardingFlow::test_button_interaction_consistency ERROR [ 74%]\ntests/test_simple.py::test_basic_functionality PASSED                    [ 76%]\ntests/test_simple.py::test_async_functionality PASSED                    [ 77%]\ntests/test_simple.py::TestBasicClass::test_class_method PASSED           [ 79%]\ntests/test_state_bug.py::TestStateManagementBug::test_state_consistency_bug_reproduction FAILED [ 81%]\ntests/test_state_bug.py::TestStateManagementBug::test_state_consistency_fixed_approach FAILED [ 83%]\ntests/test_state_bug.py::TestStateManagementBug::test_onboarding_state_flow FAILED [ 84%]\ntests/test_state_bug_simple.py::TestStateManagementBugSimple::test_state_consistency_bug_demonstration FAILED [ 86%]\ntests/test_state_bug_simple.py::TestStateManagementBugSimple::test_state_consistency_fixed_approach FAILED [ 88%]\ntests/test_state_bug_simple.py::TestStateManagementBugSimple::test_onboarding_state_transitions FAILED [ 89%]\ntests/test_state_bug_simple.py::TestStateManagementBugSimple::test_state_validation PASSED [ 91%]\ntests/test_state_management.py::TestStateManagementConsistency::test_state_manager_consistency FAILED [ 93%]\ntests/test_state_management.py::TestStateManagementConsistency::test_state_persistence_across_calls FAILED [ 94%]\ntests/test_state_management.py::TestStateManagementConsistency::test_state_manager_thread_safety FAILED [ 96%]\ntests/test_state_management.py::TestStateManagementConsistency::test_invalid_user_state_handling FAILED [ 98%]\ntests/test_state_management.py::TestStateManagementConsistency::test_state_transition_validation FAILED [100%]\n\n==================================== ERRORS ====================================\n_____ ERROR at setup of TestAdminNotifications.test_new_user_notification ______\ntests/test_admin_notifications.py:15: in admin_notifications\n    return AdminNotificationService(\"test_admin_token\", \"41107472\")\nE   TypeError: __init__() takes 1 positional argument but 3 were given\n_ ERROR at setup of TestAdminNotifications.test_new_subscription_notification __\ntests/test_admin_notifications.py:15: in admin_notifications\n    return AdminNotificationService(\"test_admin_token\", \"41107472\")\nE   TypeError: __init__() takes 1 positional argument but 3 were given\n______ ERROR at setup of TestAdminNotifications.test_payment_notification ______\ntests/test_admin_notifications.py:15: in admin_notifications\n    return AdminNotificationService(\"test_admin_token\", \"41107472\")\nE   TypeError: __init__() takes 1 positional argument but 3 were given\n___ ERROR at setup of TestAdminNotifications.test_help_request_notification ____\ntests/test_admin_notifications.py:15: in admin_notifications\n    return AdminNotificationService(\"test_admin_token\", \"41107472\")\nE   TypeError: __init__() takes 1 positional argument but 3 were given\n__ ERROR at setup of TestAdminNotifications.test_notification_error_handling ___\ntests/test_admin_notifications.py:15: in admin_notifications\n    return AdminNotificationService(\"test_admin_token\", \"41107472\")\nE   TypeError: __init__() takes 1 positional argument but 3 were given\n_ ERROR at setup of TestAdminNotifications.test_notification_with_missing_user_data _\ntests/test_admin_notifications.py:15: in admin_notifications\n    return AdminNotificationService(\"test_admin_token\", \"41107472\")\nE   TypeError: __init__() takes 1 positional argument but 3 were given\n____ ERROR at setup of TestAdminNotifications.test_notification_formatting _____\ntests/test_admin_notifications.py:15: in admin_notifications\n    return AdminNotificationService(\"test_admin_token\", \"41107472\")\nE   TypeError: __init__() takes 1 positional argument but 3 were given\n_____ ERROR at setup of TestAdminNotifications.test_multiple_notifications _____\ntests/test_admin_notifications.py:15: in admin_notifications\n    return AdminNotificationService(\"test_admin_token\", \"41107472\")\nE   TypeError: __init__() takes 1 positional argument but 3 were given\n_ ERROR at setup of TestAdminNotifications.test_notification_with_special_characters _\ntests/test_admin_notifications.py:15: in admin_notifications\n    return AdminNotificationService(\"test_admin_token\", \"41107472\")\nE   TypeError: __init__() takes 1 positional argument but 3 were given\n_ ERROR at setup of TestMessageRouting.test_start_command_routes_to_onboarding _\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n______ ERROR at setup of TestMessageRouting.test_message_routing_by_state ______\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n__ ERROR at setup of TestMessageRouting.test_callback_query_routing_by_state ___\nconftest.py:85: in mock_update_callback\n    update.message = None\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n_ ERROR at setup of TestMessageRouting.test_unknown_state_routes_to_onboarding _\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n__ ERROR at setup of TestMessageRouting.test_none_state_routes_to_onboarding ___\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n_ ERROR at setup of TestMessageRouting.test_message_routing_with_security_checks _\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n_ ERROR at setup of TestMessageRouting.test_callback_query_routing_with_security_checks _\nconftest.py:85: in mock_update_callback\n    update.message = None\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n________ ERROR at setup of TestMessageRouting.test_rate_limit_blocking _________\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n_______ ERROR at setup of TestMessageRouting.test_invalid_input_handling _______\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n_____ ERROR at setup of TestMessageRouting.test_error_handling_in_routing ______\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n_ ERROR at setup of TestOnboardingFlow.test_start_onboarding_sets_correct_state _\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n_ ERROR at setup of TestOnboardingFlow.test_welcome_message_sends_correct_content _\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n_ ERROR at setup of TestOnboardingFlow.test_continue_onboarding_button_advances_step _\nconftest.py:85: in mock_update_callback\n    update.message = None\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n_ ERROR at setup of TestOnboardingFlow.test_disclaimer_acceptance_advances_flow _\nconftest.py:85: in mock_update_callback\n    update.message = None\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n_ ERROR at setup of TestOnboardingFlow.test_age_collection_handles_valid_input _\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n_ ERROR at setup of TestOnboardingFlow.test_age_collection_handles_invalid_input _\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n____ ERROR at setup of TestOnboardingFlow.test_city_collection_stores_city _____\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n_ ERROR at setup of TestOnboardingFlow.test_onboarding_completion_sets_final_state _\nconftest.py:77: in mock_update\n    update.message = mock_message\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n___ ERROR at setup of TestOnboardingFlow.test_button_interaction_consistency ___\nconftest.py:85: in mock_update_callback\n    update.message = None\n../TelegramBot/venv/lib/python3.9/site-packages/telegram/_telegramobject.py:172: in __setattr__\n    raise AttributeError(\nE   AttributeError: Attribute `message` of class `Update` can't be set!\n=================================== FAILURES ===================================\n_________________ TestBugDemonstration.test_fix_demonstration __________________\ntests/test_bug_demonstration.py:84: in test_fix_demonstration\n    assert retrieved_state == test_state.value, f\"Expected {test_state.value}, got {retrieved_state}\"\nE   AssertionError: Expected onboarding, got None\nE   assert None == 'onboarding'\nE    +  where 'onboarding' = <UserState.ONBOARDING: 'onboarding'>.value\n_______________ TestBugDemonstration.test_fixed_onboarding_flow ________________\ntests/test_bug_demonstration.py:160: in test_fixed_onboarding_flow\n    assert retrieved_state == \"onboarding\", f\"Expected 'onboarding', got {retrieved_state}\"\nE   AssertionError: Expected 'onboarding', got None\nE   assert None == 'onboarding'\n_____________ TestDatabaseOperations.test_database_initialization ______________\ntests/test_database_operations.py:16: in test_database_initialization\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n_______________ TestDatabaseOperations.test_user_initialization ________________\ntests/test_database_operations.py:25: in test_user_initialization\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n______________ TestDatabaseOperations.test_user_state_management _______________\ntests/test_database_operations.py:46: in test_user_state_management\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n________________ TestDatabaseOperations.test_user_state_updates ________________\ntests/test_database_operations.py:67: in test_user_state_updates\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n_________________ TestDatabaseOperations.test_message_storage __________________\ntests/test_database_operations.py:88: in test_message_storage\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n_____________ TestDatabaseOperations.test_subscription_management ______________\ntests/test_database_operations.py:123: in test_subscription_management\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n___________ TestDatabaseOperations.test_focus_statements_management ____________\ntests/test_database_operations.py:146: in test_focus_statements_management\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n_________________ TestDatabaseOperations.test_task_management __________________\ntests/test_database_operations.py:179: in test_task_management\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n______________ TestDatabaseOperations.test_active_task_management ______________\ntests/test_database_operations.py:218: in test_active_task_management\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n____________ TestDatabaseOperations.test_database_concurrent_access ____________\ntests/test_database_operations.py:255: in test_database_concurrent_access\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n________ TestStateManagementBug.test_state_consistency_bug_reproduction ________\ntests/test_state_bug.py:39: in test_state_consistency_bug_reproduction\n    retrieved_data = await state_manager.get_user_state_data(12345)\nE   AttributeError: 'UserStateManager' object has no attribute 'get_user_state_data'\n_________ TestStateManagementBug.test_state_consistency_fixed_approach _________\ntests/test_state_bug.py:74: in test_state_consistency_fixed_approach\n    retrieved_data = await state_manager.get_user_state_data(12345)\nE   AttributeError: 'UserStateManager' object has no attribute 'get_user_state_data'\n______________ TestStateManagementBug.test_onboarding_state_flow _______________\ntests/test_state_bug.py:116: in test_onboarding_state_flow\n    data = await state_manager.get_user_state_data(12345)\nE   AttributeError: 'UserStateManager' object has no attribute 'get_user_state_data'\n____ TestStateManagementBugSimple.test_state_consistency_bug_demonstration _____\ntests/test_state_bug_simple.py:41: in test_state_consistency_bug_demonstration\n    assert retrieved_state == test_state, f\"Expected {test_state}, got {retrieved_state}\"\nE   AssertionError: Expected onboarding, got None\nE   assert None == 'onboarding'\n______ TestStateManagementBugSimple.test_state_consistency_fixed_approach ______\ntests/test_state_bug_simple.py:77: in test_state_consistency_fixed_approach\n    assert retrieved_state == test_state.value, f\"Expected {test_state.value}, got {retrieved_state}\"\nE   AssertionError: Expected onboarding, got None\nE   assert None == 'onboarding'\nE    +  where 'onboarding' = <UserState.ONBOARDING: 'onboarding'>.value\n________ TestStateManagementBugSimple.test_onboarding_state_transitions ________\ntests/test_state_bug_simple.py:114: in test_onboarding_state_transitions\n    assert retrieved_state == state_string, f\"Expected {state_string}, got {retrieved_state}\"\nE   AssertionError: Expected onboarding, got None\nE   assert None == 'onboarding'\n________ TestStateManagementConsistency.test_state_manager_consistency _________\ntests/test_state_management.py:22: in test_state_manager_consistency\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n______ TestStateManagementConsistency.test_state_persistence_across_calls ______\ntests/test_state_management.py:51: in test_state_persistence_across_calls\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n_______ TestStateManagementConsistency.test_state_manager_thread_safety ________\ntests/test_state_management.py:77: in test_state_manager_thread_safety\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n_______ TestStateManagementConsistency.test_invalid_user_state_handling ________\ntests/test_state_management.py:103: in test_invalid_user_state_handling\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n_______ TestStateManagementConsistency.test_state_transition_validation ________\ntests/test_state_management.py:118: in test_state_transition_validation\n    await db_manager.initialize_database()\nE   AttributeError: 'DatabaseManager' object has no attribute 'initialize_database'\n- generated xml file: /Users/dmitrypavlyuchenkov/HackReality-MainBot/test_results.xml -\n\n---------- coverage: platform darwin, python 3.9.6-final-0 -----------\nCoverage HTML written to dir htmlcov\nCoverage JSON written to file coverage.json\n\n=========================== short test summary info ============================\nFAILED tests/test_bug_demonstration.py::TestBugDemonstration::test_fix_demonstration\nFAILED tests/test_bug_demonstration.py::TestBugDemonstration::test_fixed_onboarding_flow\nFAILED tests/test_database_operations.py::TestDatabaseOperations::test_database_initialization\nFAILED tests/test_database_operations.py::TestDatabaseOperations::test_user_initialization\nFAILED tests/test_database_operations.py::TestDatabaseOperations::test_user_state_management\nFAILED tests/test_database_operations.py::TestDatabaseOperations::test_user_state_updates\nFAILED tests/test_database_operations.py::TestDatabaseOperations::test_message_storage\nFAILED tests/test_database_operations.py::TestDatabaseOperations::test_subscription_management\nFAILED tests/test_database_operations.py::TestDatabaseOperations::test_focus_statements_management\nFAILED tests/test_database_operations.py::TestDatabaseOperations::test_task_management\nFAILED tests/test_database_operations.py::TestDatabaseOperations::test_active_task_management\nFAILED tests/test_database_operations.py::TestDatabaseOperations::test_database_concurrent_access\nFAILED tests/test_state_bug.py::TestStateManagementBug::test_state_consistency_bug_reproduction\nFAILED tests/test_state_bug.py::TestStateManagementBug::test_state_consistency_fixed_approach\nFAILED tests/test_state_bug.py::TestStateManagementBug::test_onboarding_state_flow\nFAILED tests/test_state_bug_simple.py::TestStateManagementBugSimple::test_state_consistency_bug_demonstration\nFAILED tests/test_state_bug_simple.py::TestStateManagementBugSimple::test_state_consistency_fixed_approach\nFAILED tests/test_state_bug_simple.py::TestStateManagementBugSimple::test_onboarding_state_transitions\nFAILED tests/test_state_management.py::TestStateManagementConsistency::test_state_manager_consistency\nFAILED tests/test_state_management.py::TestStateManagementConsistency::test_state_persistence_across_calls\nFAILED tests/test_state_management.py::TestStateManagementConsistency::test_state_manager_thread_safety\nFAILED tests/test_state_management.py::TestStateManagementConsistency::test_invalid_user_state_handling\nFAILED tests/test_state_management.py::TestStateManagementConsistency::test_state_transition_validation\nERROR tests/test_admin_notifications.py::TestAdminNotifications::test_new_user_notification\nERROR tests/test_admin_notifications.py::TestAdminNotifications::test_new_subscription_notification\nERROR tests/test_admin_notifications.py::TestAdminNotifications::test_payment_notification\nERROR tests/test_admin_notifications.py::TestAdminNotifications::test_help_request_notification\nERROR tests/test_admin_notifications.py::TestAdminNotifications::test_notification_error_handling\nERROR tests/test_admin_notifications.py::TestAdminNotifications::test_notification_with_missing_user_data\nERROR tests/test_admin_notifications.py::TestAdminNotifications::test_notification_formatting\nERROR tests/test_admin_notifications.py::TestAdminNotifications::test_multiple_notifications\nERROR tests/test_admin_notifications.py::TestAdminNotifications::test_notification_with_special_characters\nERROR tests/test_message_routing.py::TestMessageRouting::test_start_command_routes_to_onboarding\nERROR tests/test_message_routing.py::TestMessageRouting::test_message_routing_by_state\nERROR tests/test_message_routing.py::TestMessageRouting::test_callback_query_routing_by_state\nERROR tests/test_message_routing.py::TestMessageRouting::test_unknown_state_routes_to_onboarding\nERROR tests/test_message_routing.py::TestMessageRouting::test_none_state_routes_to_onboarding\nERROR tests/test_message_routing.py::TestMessageRouting::test_message_routing_with_security_checks\nERROR tests/test_message_routing.py::TestMessageRouting::test_callback_query_routing_with_security_checks\nERROR tests/test_message_routing.py::TestMessageRouting::test_rate_limit_blocking\nERROR tests/test_message_routing.py::TestMessageRouting::test_invalid_input_handling\nERROR tests/test_message_routing.py::TestMessageRouting::test_error_handling_in_routing\nERROR tests/test_onboarding_flow.py::TestOnboardingFlow::test_start_onboarding_sets_correct_state\nERROR tests/test_onboarding_flow.py::TestOnboardingFlow::test_welcome_message_sends_correct_content\nERROR tests/test_onboarding_flow.py::TestOnboardingFlow::test_continue_onboarding_button_advances_step\nERROR tests/test_onboarding_flow.py::TestOnboardingFlow::test_disclaimer_acceptance_advances_flow\nERROR tests/test_onboarding_flow.py::TestOnboardingFlow::test_age_collection_handles_valid_input\nERROR tests/test_onboarding_flow.py::TestOnboardingFlow::test_age_collection_handles_invalid_input\nERROR tests/test_onboarding_flow.py::TestOnboardingFlow::test_city_collection_stores_city\nERROR tests/test_onboarding_flow.py::TestOnboardingFlow::test_onboarding_completion_sets_final_state\nERROR tests/test_onboarding_flow.py::TestOnboardingFlow::test_button_interaction_consistency\n=================== 23 failed, 8 passed, 28 errors in 1.26s ====================\n",
  "stderr": "",
  "success": false,
  "test_count": 0,
  "failure_count": 0
}